### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Chealer** [nunibaranes/debugger-timeout-chrome-extension#3]
It could be quite interesting to licence this code in a way which at least allows redistribution. Without any explicit license, the extension's presence in the Web Store [merely implies that](https://developer.chrome.com/docs/webstore/program-policies/terms#license):

> 5.2 You grant to the user a non-exclusive, worldwide, and perpetual license to perform, display, and use the Products and any content contained in, accessed by, or transmitted through the Products in connection with Google Chrome. If you choose, you may include a separate end user license agreement (EULA) in your Product that will govern the user's rights to the Products in lieu of the previous sentence.

**Comment by nunibaranes** [comment]
Thank you, @Chealer, for your comment.
I've updated the license 👍

**Comment by Chealer** [comment]
MIT! Wow!🥳
🙏Thank you so much @nunibaranes , I will be sure to try the extension next time I hit this problem (and I'm sure that will happen sooner rather than later😏)
🙏🙏
