### ISSUE TITLE
Unclear description

### ISSUE THREAD

**Issue by Chealer** [nunibaranes/debugger-timeout-chrome-extension#5]
The README contains the following description of this extension's usage:

> How to use:
> 1. Open the Chrome devtools, so that the extension will work properly.
> 2. Set the number of seconds.
> 3. Run the debugger. 

The third step is unclear.

It would greatly help to be more specific or to include an example, perhaps as a screencast.

**Comment by nunibaranes** [comment]
Thank you, @Chealer, for your comment.
I’ve updated and expanded the descriptions of the sections. I hope they are clearer now. Let me know if there’s anything else I can clarify further.

**Comment by Chealer** [comment]
Thank you @nunibaranes ... so simple in the end, but your edit makes it so much more clear now 🙏
